function  iou_plot( iou_vector )

sortedIoU = sort(iou_vector,'descend');

figure;
hold on;
plot(sortedIoU, linspace(0, length(sortedIoU), length(sortedIoU)));

            hTitle  = title ('Success Plot');
            hYLabel = ylabel('Success');
            hXLabel = xlabel('IoU');
            
            set([hTitle, hXLabel, hYLabel], ...
           'FontName'   , 'AvantGarde');
            set([hXLabel, hYLabel]  , ...
            'FontSize'   , 10          );
            set( hTitle                    , ...
            'FontSize'   , 12          , ...
            'FontWeight' , 'bold'      );
            set( gca                       , ...
            'FontName'   , 'Helvetica' );

            set([gca]             , ...
            'FontSize'   , 8           );


            set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'TickLength'  , [.02 .02] , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         );   

drawnow

end 