function  tre_plot( iou_vec , exec_type, dir, sca)
strDir = '';
strSca = '';
switch(dir)
    case 1
        strDir = 'Up'
    case 2
        strDir = 'Down'
    case 3
        strDir = 'Left'
    case 4
        strDir = 'Right'
end

switch(sca)
    case 1
        strSca = '0.8';
    case 2
        strSca = '0.9';
    case 3
        strSca = '1.1';
    case 4
        strSca = '1.2';
end

figure;
hold on;


modAux = mod(length(iou_vec), 5);

interval = (length(iou_vec)-modAux)/5;

v1 = iou_vec(1:interval);
v2 = iou_vec(interval+1: interval*2);
v3 = iou_vec(interval*2+1 : interval*3);
v4 = iou_vec(interval*3+1 : interval*4);
v5 = iou_vec(interval*4+1 : interval*5);


 plot(sort(v1, 'descend'), linspace(0, length(v1),length(v1)), ...
     sort(v2, 'descend'), linspace(0, length(v2),length(v2)), ...
     sort(v3, 'descend'), linspace(0, length(v3),length(v3)), ...
     sort(v4, 'descend'), linspace(0, length(v4),length(v4)), ...
     sort(v5, 'descend'), linspace(0, length(v5),length(v5)));  
 
switch exec_type
    %normal
    case 1
            hTitle  = title ('Normal Execution');
            hYLabel = ylabel('Success');
            hXLabel = xlabel('IoU');
            
            set([hTitle, hXLabel, hYLabel], ...
           'FontName'   , 'AvantGarde');
            legend('1st Frame Set','2nd Frame Set', '3rd Frame Set', '4th Frame Set', '5th Frame Set');
            set([hXLabel, hYLabel]  , ...
            'FontSize'   , 10          );
            set( hTitle                    , ...
            'FontSize'   , 12          , ...
            'FontWeight' , 'bold'      );
            set( gca                       , ...
            'FontName'   , 'Helvetica' );

            set([gca]             , ...
            'FontSize'   , 8           );


            set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'TickLength'  , [.02 .02] , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         );        
    %TRE
    case 2
            hTitle  = title ('TRE Execution');
            hYLabel = ylabel('Success');
            hXLabel = xlabel('IoU');
            
            set([hTitle, hXLabel, hYLabel], ...
           'FontName'   , 'AvantGarde');
            legend('1st Frame Set','2nd Frame Set', '3rd Frame Set', '4th Frame Set', '5th Frame Set');
            set([hXLabel, hYLabel]  , ...
            'FontSize'   , 10          );
            set( hTitle                    , ...
            'FontSize'   , 12          , ...
            'FontWeight' , 'bold'      );
            set( gca                       , ...
            'FontName'   , 'Helvetica' );

            set([gca]             , ...
            'FontSize'   , 8           );


            set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'TickLength'  , [.02 .02] , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         );      
    %SRE    
    case 3
            a = strcat('SRE Execution - Direction: ', strDir, ' - Scale: ', strSca);
            hTitle  = title (a);
            hYLabel = ylabel('Success');
            hXLabel = xlabel('IoU');
            
            set([hTitle, hXLabel, hYLabel], ...
           'FontName'   , 'AvantGarde');
            legend('1st Frame Set','2nd Frame Set', '3rd Frame Set', '4th Frame Set', '5th Frame Set');
            set([hXLabel, hYLabel]  , ...
            'FontSize'   , 10          );
            set( hTitle                    , ...
            'FontSize'   , 12          , ...
            'FontWeight' , 'bold'      );
            set( gca                       , ...
            'FontName'   , 'Helvetica' );

            set([gca]             , ...
            'FontSize'   , 8           );


            set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'TickLength'  , [.02 .02] , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         );      
        
end

drawnow

disp(v1);

end 

